"""Food system rules for irrigation, food security effects, and recovery."""


def effective_irrigation_threshold(base_threshold: float, multiplier: float) -> float:
    """Return the irrigation threshold after modifiers are applied."""
    return max(0.0, base_threshold * (1.0 + multiplier))


def food_output_bonus(base_food: float, yield_multiplier: float) -> float:
    """Return additional food generated by yield modifiers."""
    return max(0.0, base_food * max(0.0, yield_multiplier - 1.0))


def recovery_bonus(water_after_dependencies: float, irrigation_threshold: float, bonus: float) -> float:
    """Return deterministic food recovery when water remains comfortably safe."""
    if water_after_dependencies > irrigation_threshold:
        return bonus
    return 0.0
